<a href="https://colab.research.google.com/github/atharvapatil1210/100-Days-Code-Challange/blob/main/numpy_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
pip install pandas

In [ ]:
import numpy as ns

In [ ]:
print("Hello world")

Hello world


In [ ]:
import sklearn

###NUMPY

In [ ]:
import numpy as np

In [ ]:
myarr = np.array([[3,6,32,7]],np.int8)

In [ ]:
myarr

array([ 3,  6, 32,  7], dtype=int8)

In [ ]:
type(myarr)

numpy.ndarray

In [ ]:
myarr[0,3]

7

In [ ]:
myarr.dtype

dtype('int8')

In [ ]:
myarr[0,1] = 45

In [ ]:
listarray = np.array([[1,2,3],[5,6,7],[7,8,9]])

In [ ]:
listarray

array([[1, 2, 3],
       [5, 6, 7],
       [7, 8, 9]])

In [ ]:
listarray.dtype

dtype('int64')

In [ ]:
ls = listarray.T

In [ ]:
ls

array([[1, 5, 7],
       [2, 6, 8],
       [3, 7, 9]])

In [ ]:
ls.size

9

In [ ]:
zeros = np.zeros((2,5))

In [ ]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
rng = np.arrange(15)

AttributeError: module 'numpy' has no attribute 'arrange'